name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MLflow server
      run: |
        mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 10  # Give the server some time to start

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: |
        export MLFLOW_TRACKING_URI=http://127.0.0.1:5000
        cd tests
        python -m unittest discover tests


    # Optional deployment step
    - name: Deploy
      run: |
        ./deploy.sh  # or whatever your deployment script/command is
