name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MLflow server
      run: |
        mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 10  # Give the server some time to start

    - name: Start Gunicorn server
      run: |
        gunicorn main:app &
        sleep 10  # Give the server some time to start

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: python -m unittest tests/test_functions.py
    # Optional deployment step
    - name: Grant execute permission for deploy.sh
      run: chmod +x deploy.sh

    - name: Run deploy.sh
      run: ./deploy.sh
